// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zoo.Api.Data;

#nullable disable

namespace Zoo.Api.Migrations
{
    [DbContext(typeof(ZooDbContext))]
    [Migration("20231118230734_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Zoo.Api.Entities.ZooAnimal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Species")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ZooAnimals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 4,
                            Gender = "Female",
                            Name = "Mia",
                            Species = "Lion"
                        },
                        new
                        {
                            Id = 2,
                            Age = 3,
                            Gender = "Male",
                            Name = "Mason",
                            Species = "Jaguar"
                        },
                        new
                        {
                            Id = 3,
                            Age = 2,
                            Gender = "Male",
                            Name = "Henry",
                            Species = "Orangutan"
                        },
                        new
                        {
                            Id = 4,
                            Age = 1,
                            Gender = "Male",
                            Name = "Rae",
                            Species = "Bear"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
